import { invokeLLM } from './llm';
import type { LogoStyle } from './generateLogoImage';

export interface LogoBriefInput {
  businessName: string;
  category: string;
  city: string;
  competitorLogoInsight: string;
  ownLogoCritique: string;
  changeFeedback?: string; // owner's requested change to a previous AI-generated draft, if this is a revision
  style?: LogoStyle; // 'creative' (icon, default) or 'wordmark' (business name as the design)
}

function styleInstruction(style: LogoStyle, businessName: string): string {
  if (style === 'wordmark') {
    return 'Write ONE English design brief (25-50 words) for a wordmark logo — the business name IS the design, '
      + `rendered as the literal text "${businessName}" in whatever script it's already written in. Describe the `
      + 'typography (weight, style), letter arrangement, and color palette; keep it minimal, no separate icon or '
      + 'imagery beyond the lettering itself.';
  }
  return 'Write ONE English design brief (25-50 words) for a NEW logo/icon for this business that fixes the '
    + 'problems above while fitting the sector — describe concrete visual elements: shape/icon motif, color '
    + 'palette, style. Do NOT mention the business name as text to render (logos generated by AI tools render '
    + 'text poorly).';
}

/**
 * Turns the Hebrew competitor-logo pattern + the critique of the business's
 * own current logo into a single English design brief for the image-gen
 * providers (which respond far better to English, descriptive prompts).
 * Falls back to a generic brand-icon brief if the LLM call fails.
 */
export async function buildLogoDesignBrief(input: LogoBriefInput): Promise<string> {
  const style: LogoStyle = input.style === 'wordmark' ? 'wordmark' : 'creative';
  try {
    const raw = await invokeLLM({
      model: 'sonnet',
      maxTokens: 200,
      skipCache: true,
      prompt: `You are a brand designer writing a brief for an AI logo-generation tool.

Business: "${input.businessName}" — ${input.category} in ${input.city}
Visual pattern common across this business's competitors' logos: ${input.competitorLogoInsight}
What's wrong with this business's current logo: ${input.ownLogoCritique}
${input.changeFeedback ? `\nThe owner reviewed a previous AI-generated draft and asked for this specific change: "${input.changeFeedback}". The new brief must incorporate this.\n` : ''}
${styleInstruction(style, input.businessName)} The literal business name text may appear in your brief in its original script — everything else in English. Return ONLY the brief, no explanation, no quotes.`,
    });

    const text = typeof raw === 'string' ? raw : (raw?.text ?? JSON.stringify(raw ?? ''));
    const cleaned = text.replace(/^["']|["']$/g, '').replace(/\n/g, ' ').trim();
    if (cleaned.length > 15) return cleaned.slice(0, 400);
  } catch (err: any) {
    console.warn('[buildLogoDesignBrief] failed:', err.message);
  }

  return style === 'wordmark'
    ? `Wordmark logo rendering the text "${input.businessName}" in bold clean lettering, minimal color palette`
    : `Modern minimalist brand icon for a ${input.category} business, clean geometric shape, professional color palette`;
}
