import { invokeLLM } from './llm';

export interface LogoBriefInput {
  businessName: string;
  category: string;
  city: string;
  competitorLogoInsight: string;
  ownLogoCritique: string;
  changeFeedback?: string; // owner's requested change to a previous AI-generated draft, if this is a revision
}

/**
 * Turns the Hebrew competitor-logo pattern + the critique of the business's
 * own current logo into a single English design brief for the image-gen
 * providers (which respond far better to English, descriptive prompts).
 * Falls back to a generic brand-icon brief if the LLM call fails.
 */
export async function buildLogoDesignBrief(input: LogoBriefInput): Promise<string> {
  try {
    const raw = await invokeLLM({
      model: 'sonnet',
      maxTokens: 200,
      skipCache: true,
      prompt: `You are a brand designer writing a brief for an AI logo-generation tool.

Business: "${input.businessName}" — ${input.category} in ${input.city}
Visual pattern common across this business's competitors' logos: ${input.competitorLogoInsight}
What's wrong with this business's current logo: ${input.ownLogoCritique}
${input.changeFeedback ? `\nThe owner reviewed a previous AI-generated draft and asked for this specific change: "${input.changeFeedback}". The new brief must incorporate this.\n` : ''}
Write ONE English design brief (25-50 words) for a NEW logo/icon for this business that fixes the problems above while fitting the sector — describe concrete visual elements: shape/icon motif, color palette, style. English only. Do NOT mention the business name as text to render (logos generated by AI tools render text poorly). Return ONLY the brief, no explanation, no quotes.`,
    });

    const text = typeof raw === 'string' ? raw : (raw?.text ?? JSON.stringify(raw ?? ''));
    const cleaned = text.replace(/^["']|["']$/g, '').replace(/\n/g, ' ').trim();
    if (cleaned.length > 15) return cleaned.slice(0, 400);
  } catch (err: any) {
    console.warn('[buildLogoDesignBrief] failed:', err.message);
  }

  return `Modern minimalist brand icon for a ${input.category} business, clean geometric shape, professional color palette`;
}
