import { Request, Response } from 'express';
import { prisma } from '../../db';
import { writeAutomationLog } from '../../lib/automationLog';
import { scoreOwnBio } from '../../lib/scoreOwnBio';
import { scoreOwnPicture } from '../../lib/scoreOwnPicture';

const BIO_STRUCTURE_MAX = 20;
const BIO_PERSUASIVENESS_MAX = 30;
const PICTURE_TECHNICAL_MAX = 20;
const PICTURE_PROFESSIONALISM_MAX = 30;

const BIO_MIN_LENGTH = 30;  // matches SocialProfileSuggestions.jsx's own threshold
const BIO_FULL_LENGTH = 120; // length at which the structure score hits its cap

// Same check as isFacebookAutoBio in src/components/competitors/socialShared.jsx,
// ported server-side — a platform-generated Intro isn't real bio content no
// matter how long it is.
function isAutoGeneratedBio(bio: string, followerCount: number | null, checkinCount: number | null): boolean {
  const markers: string[] = [];
  if (followerCount != null) markers.push(String(followerCount));
  if (checkinCount != null) markers.push(String(checkinCount));
  return markers.length > 0 && markers.every(m => bio.includes(m));
}

function scoreBioStructure(profile: { bio: string | null; follower_count: number | null; checkin_count: number | null; external_url: string | null }): number {
  const bio = profile.bio?.trim();
  if (!bio) return 0;

  const isAuto = isAutoGeneratedBio(bio, profile.follower_count, profile.checkin_count);
  const lengthRatio = Math.max(0, Math.min(1, (bio.length - BIO_MIN_LENGTH) / (BIO_FULL_LENGTH - BIO_MIN_LENGTH)));
  const lengthScore = bio.length < BIO_MIN_LENGTH ? 0 : lengthRatio * 14; // up to 14/20 for length alone
  const linkBonus = profile.external_url ? 3 : 0;
  let score = lengthScore + linkBonus + 3; // +3 baseline for having any real bio at all
  if (isAuto) score = Math.min(score, 5); // auto-generated text caps low regardless of length
  return Math.round(Math.min(BIO_STRUCTURE_MAX, score));
}

function scorePictureTechnical(profile: { profile_picture_url: string | null; is_business_account: boolean | null; cover_photo_url: string | null }): number {
  if (!profile.profile_picture_url) return 0;
  let score = 12; // presence baseline
  if (profile.is_business_account) score += 4;
  if (profile.cover_photo_url) score += 4;
  return Math.round(Math.min(PICTURE_TECHNICAL_MAX, score));
}

/**
 * calculateProfileScore
 *
 * 0-100 score for a business's OWN social profile (bio + profile picture),
 * broken into 4 categories — 2 deterministic (structure/presence, computed
 * from BusinessSocialProfile fields already synced by the social snapshot
 * pipeline) and 2 LLM-judged (persuasiveness, professionalism/brand-fit).
 * Runs standalone — unlike critiqueLogo/suggestBioFix it does NOT require
 * content_trends_bio_insight/content_trends_logo_insight to exist first, so
 * it works the very first time a user opens the profile-analysis modal.
 *
 * Body: { businessProfileId, platform }
 * Returns: the upserted ProfileScore row (+ parsed improvements array)
 */
export async function calculateProfileScore(req: Request, res: Response) {
  const { businessProfileId, platform } = req.body;
  if (!businessProfileId) return res.status(400).json({ error: 'Missing businessProfileId' });
  if (!platform) return res.status(400).json({ error: 'Missing platform' });

  const startTime = new Date().toISOString();
  try {
    const [profile, ownProfile] = await Promise.all([
      prisma.businessProfile.findUnique({ where: { id: businessProfileId } }),
      prisma.businessSocialProfile.findFirst({ where: { linked_business: businessProfileId, platform } }),
    ]);
    if (!profile) return res.status(404).json({ error: 'Business not found' });
    if (!ownProfile) return res.status(404).json({ error: `No ${platform} profile found for this business` });

    const bioStructureScore = scoreBioStructure(ownProfile);
    const pictureTechnicalScore = scorePictureTechnical(ownProfile);

    const [bioResult, pictureResult] = await Promise.all([
      ownProfile.bio?.trim()
        ? scoreOwnBio({ businessName: profile.name, category: profile.category, city: profile.city, bio: ownProfile.bio })
        : Promise.resolve({ score: 0, reasoning: 'אין ביו' }),
      ownProfile.profile_picture_url
        ? scoreOwnPicture({ businessName: profile.name, category: profile.category, platform, imageUrl: ownProfile.profile_picture_url })
        : Promise.resolve({ score: 0, reasoning: 'אין תמונת פרופיל' }),
    ]);

    const bioPersuasivenessScore = Math.round((bioResult.score / 100) * BIO_PERSUASIVENESS_MAX);
    const picturePersuasivenessScore = Math.round((pictureResult.score / 100) * PICTURE_PROFESSIONALISM_MAX);

    const overallScore = bioStructureScore + bioPersuasivenessScore + pictureTechnicalScore + picturePersuasivenessScore;

    const improvements: { area: string; text: string }[] = [];
    if (!ownProfile.bio?.trim()) improvements.push({ area: 'bio', text: 'לא הוגדר ביו' });
    else if (bioResult.reasoning) improvements.push({ area: 'bio', text: bioResult.reasoning });
    if (!ownProfile.external_url) improvements.push({ area: 'bio', text: 'אין קישור בביו' });
    if (!ownProfile.profile_picture_url) improvements.push({ area: 'picture', text: 'אין תמונת פרופיל' });
    else if (pictureResult.reasoning) improvements.push({ area: 'picture', text: pictureResult.reasoning });

    const scoreData = {
      linked_business: businessProfileId,
      platform,
      overall_score: overallScore,
      bio_structure_score: bioStructureScore,
      bio_persuasiveness_score: bioPersuasivenessScore,
      picture_technical_score: pictureTechnicalScore,
      picture_professionalism_score: picturePersuasivenessScore,
      improvements: JSON.stringify(improvements),
      snapshot_date: new Date().toISOString(),
    };

    const existing = await prisma.profileScore.findFirst({ where: { linked_business: businessProfileId, platform } });
    const row = existing
      ? await prisma.profileScore.update({ where: { id: existing.id }, data: scoreData })
      : await prisma.profileScore.create({ data: scoreData });

    await writeAutomationLog('calculateProfileScore', businessProfileId, startTime, 1);
    return res.json({ ...row, improvements });
  } catch (err: any) {
    console.error('[calculateProfileScore]', err.message);
    await writeAutomationLog('calculateProfileScore', businessProfileId, startTime, 0, 'failed', err.message);
    return res.status(500).json({ error: err.message });
  }
}
