import { Request, Response } from 'express';
import { prisma } from '../../db';
import { invokeLLM } from '../../lib/llm';
import { tavilySearch, isTavilyRateLimited } from '../../lib/tavily';
import { writeAutomationLog } from '../../lib/automationLog';
import { shouldSkipAgent, setLastRun } from '../../lib/agentCache';

const MIN_INTERVAL_MS = 12 * 60 * 60 * 1000; // 12 hours

const TYPE_ICON: Record<string, string> = {
  concert: '🎵', conference: '🎙️', festival: '🎪', market: '🛒',
  sports: '⚽', community: '🤝', exhibition: '🖼️', other: '📍',
};

/**
 * findLocalEvents — discovers upcoming concerts, festivals and events
 * near the business location using targeted Tavily searches on Israeli
 * event listing sites (Timeout, goout.net, icast, etc.).
 *
 * Each found event gets a business-specific CTA generated by the LLM.
 * Runs automatically as part of runFullScan (every 12h).
 */
export async function findLocalEvents(req: Request, res: Response) {
  const { businessProfileId } = req.body;
  if (!businessProfileId) return res.status(400).json({ error: 'Missing businessProfileId' });

  if (shouldSkipAgent(businessProfileId, 'findLocalEvents', MIN_INTERVAL_MS)) {
    return res.json({ signals_created: 0, skipped: true, reason: 'ran_recently' });
  }

  const startTime = new Date().toISOString();
  try {
    const profile = await prisma.businessProfile.findFirst({ where: { id: businessProfileId } });
    if (!profile) return res.status(404).json({ error: 'No business profile' });

    const { name, category, city } = profile;
    const now = new Date();
    const month      = now.toLocaleDateString('he-IL', { month: 'long' });
    const nextMonth  = new Date(now.getTime() + 30 * 86400000).toLocaleDateString('he-IL', { month: 'long' });
    const yearStr    = now.getFullYear();

    // Derive a region label for small cities that aren't indexed heavily
    // e.g. "זכרון יעקב" → also search "כרמל", "שרון"; "אילת" → "נגב" etc.
    const REGION_MAP: Record<string, string> = {
      'זכרון יעקב': 'כרמל שרון קיסריה',
      'בנימינה': 'כרמל שרון קיסריה',
      'עתלית': 'כרמל חיפה',
      'מגדל העמק': 'עמק יזרעאל',
      'עפולה': 'עמק יזרעאל',
      'כפר סבא': 'שרון',
      'רעננה': 'שרון',
      'הרצליה': 'גוש דן',
      'נס ציונה': 'גוש דן',
      'אשדוד': 'שפלה',
      'אשקלון': 'שפלה',
      'באר שבע': 'נגב',
      'אילת': 'נגב',
    };
    const regionTerms = REGION_MAP[city] || '';

    if (isTavilyRateLimited()) {
      return res.json({ signals_created: 0, message: 'Tavily rate limited' });
    }

    // ── Targeted queries: Israeli event listing sites + regional search ────────
    const areaTerms = [city, regionTerms].filter(Boolean).join(' ');
    const queries = [
      // ── Ticket / event aggregator sites ──────────────────────────────────────
      `site:kupat.co.il ${city} ${month} ${nextMonth}`,
      `site:leaan.co.il הופעה פסטיבל אירוע ${areaTerms} ${month} ${yearStr}`,
      `site:timeout.co.il הופעות פסטיבלים ${city} ${month} ${nextMonth}`,
      `site:goout.net הופעה פסטיבל ${areaTerms} ${month} ${yearStr}`,
      // ── General Hebrew search — city + region ─────────────────────────────
      `הופעה זמר להקה פסטיבל אירוע ${areaTerms} ${month} ${nextMonth} ${yearStr} כרטיסים`,
      // ── Venue types for the area (amphitheaters, wineries, cultural centers) ─
      `אמפיתיאטרון מרכז תרבות יקב ${areaTerms} הופעה אירוע ${month} ${yearStr}`,
      // ── Free / open events ────────────────────────────────────────────────
      `אירוע חינם ירייד שוק ${areaTerms} ${month} ${yearStr}`,
    ];

    const allResults: any[] = [];
    for (const q of queries) {
      if (isTavilyRateLimited()) break;
      const results = await tavilySearch(q, 4);
      allResults.push(...results);
    }

    // Deduplicate by URL
    const seen = new Set<string>();
    const unique = allResults.filter(r => {
      if (!r.url || seen.has(r.url)) return false;
      seen.add(r.url);
      return true;
    });

    if (unique.length === 0) {
      setLastRun(businessProfileId, 'findLocalEvents');
      await writeAutomationLog('findLocalEvents', businessProfileId, startTime, 0);
      return res.json({ signals_created: 0 });
    }

    const context = unique.slice(0, 15)
      .map(r => `[${r.url}]\n${r.title || ''}: ${(r.content || '').slice(0, 250)}`)
      .join('\n\n');

    // ── LLM: extract specific events with artist/band names and real dates ─────
    let events: any[] = [];
    try {
      const analysis: any = await invokeLLM({
        model: 'sonnet',
        maxTokens: 900,
        skipCache: true,
        prompt: `אתה מומחה אירועים בישראל. זהה אירועים ספציפיים אמיתיים בטקסט הבא שיכולים לייצר תנועה לעסק "${name}" (${category} ב${city} ואזור).

טקסט:
${context.slice(0, 4500)}

חוקים:
- שם האירוע חייב להיות ספציפי: "הופעת אייגל" לא "הופעה", "פסטיבל הג'אז" לא "פסטיבל"
- כלול שם האמן/להקה/פסטיבל אם מוזכר
- תאריך: אם יש תאריך מדויק — השתמש בו. אם יש רק "מאי", "החודש", "הקרוב" — הכנס את ה-1 של אותו חודש כ-date_iso. רק אם אין שום מידע על תאריך — דלג על האירוע
- קבל אירועים גם מעיירות קרובות (רדיוס 30 ק"מ) — לא רק מהעיר עצמה
- רק אירועים בחודשיים הקרובים
- הזדמנות עסקית: ספציפית לסקטור "${category}" — מה הלקוחות שיגיעו יצטרכו מ"${name}"?

החזר JSON בלבד:
{"events":[{
  "name": "שם ספציפי של האירוע / האמן / הפסטיבל",
  "date_iso": "YYYY-MM-DD",
  "date_text": "תאריך קריא בעברית",
  "venue": "מיקום האירוע",
  "type": "concert|festival|market|sports|exhibition|community|conference|other",
  "artist_or_headliner": "שם האמן / ראש הלהקה / שם הפסטיבל",
  "expected_crowd": "large|medium|small",
  "business_opportunity": "הזדמנות ספציפית ל${category} — עד 10 מילים",
  "source_url": "URL המקור"
}]}
אם אין שום אירוע שניתן לזהות — החזר {"events":[]}`,
        response_json_schema: { type: 'object' },
      });
      const currentMonthIso = now.toISOString().slice(0, 8) + '01';
      events = (analysis?.events || [])
        .filter((e: any) => e.name)
        .map((e: any) => ({
          ...e,
          // If LLM returned no date_iso, use first of current month as fallback
          date_iso: e.date_iso || currentMonthIso,
        }));
    } catch (_) {}

    if (events.length === 0) {
      setLastRun(businessProfileId, 'findLocalEvents');
      await writeAutomationLog('findLocalEvents', businessProfileId, startTime, 0);
      return res.json({ signals_created: 0 });
    }

    // ── Dedup against existing local_event signals (14 days) ─────────────────
    const existing = await prisma.marketSignal.findMany({
      where: {
        linked_business: businessProfileId,
        category: 'local_event',
        detected_at: { gte: new Date(Date.now() - 14 * 86400000).toISOString() },
      },
      select: { summary: true },
    });
    const existingNames = new Set(existing.map(s => s.summary.toLowerCase()));

    let created = 0;
    for (const ev of events.slice(0, 8)) {
      if (existingNames.has(ev.name.toLowerCase())) continue;

      // Skip past events
      if (ev.date_iso && new Date(ev.date_iso).getTime() < Date.now() - 86400000) continue;

      const icon = TYPE_ICON[ev.type] || '📍';
      const daysAway = ev.date_iso
        ? Math.ceil((new Date(ev.date_iso).getTime() - Date.now()) / 86400000)
        : null;

      // Generate business-specific CTA
      let prefilledText = '';
      try {
        const ctaRes = await invokeLLM({
          model: 'haiku',
          maxTokens: 180,
          prompt: `כתוב פוסט שיווק קצר (2-3 שורות) לעסק "${name}" (${category} ב${city}) לרגל האירוע הקרוב: "${ev.name}"${ev.artist_or_headliner ? ` עם ${ev.artist_or_headliner}` : ''} ב${ev.venue || city}${daysAway ? ` (בעוד ${daysAway} ימים)` : ''}.
הזדמנות: ${ev.business_opportunity}
מבנה: Hook + ערך ספציפי + CTA. עברית בלבד, עם אמוג'י. כתוב רק את הפוסט.`,
        });
        prefilledText = typeof ctaRes === 'string' ? ctaRes.trim() : '';
      } catch (_) {}

      await prisma.marketSignal.create({
        data: {
          summary: ev.name,
          category: 'local_event',
          impact_level: ev.expected_crowd === 'large' ? 'high' : 'medium',
          recommended_action: ev.business_opportunity || `נצל את ${ev.name}`,
          confidence: ev.source_url ? 80 : 65,
          source_signals: 'tavily_local_search',
          source_description: JSON.stringify({
            event_type:           ev.type,
            artist_or_headliner:  ev.artist_or_headliner || null,
            venue:                ev.venue || null,
            date_text:            ev.date_text || null,
            event_date:           ev.date_iso || null,
            days_away:            daysAway,
            source_url:           ev.source_url || null,
            action_type:          'social_post',
            action_label:         `${icon} ${ev.name}`,
            prefilled_text:       prefilledText,
            time_minutes:         10,
          }),
          agent_name: `${icon} ${ev.name}`,
          is_read: false,
          detected_at: new Date().toISOString(),
          linked_business: businessProfileId,
        },
      }).catch(() => {});

      existingNames.add(ev.name.toLowerCase());
      created++;
    }

    setLastRun(businessProfileId, 'findLocalEvents');
    await writeAutomationLog('findLocalEvents', businessProfileId, startTime, created);
    return res.json({ signals_created: created, events_found: events.length });

  } catch (err: any) {
    console.error('[findLocalEvents] error:', err.message);
    await writeAutomationLog('findLocalEvents', businessProfileId, startTime, 0, 'failed', err.message);
    return res.status(500).json({ error: err.message });
  }
}
