import { Request, Response } from 'express';
import { prisma } from '../../db';
import { invokeLLM } from '../../lib/llm';
import { tavilySearch, isTavilyRateLimited } from '../../lib/tavily';
import { writeAutomationLog } from '../../lib/automationLog';
import { shouldSkipAgent, setLastRun } from '../../lib/agentCache';
import { publishEvent } from '../../lib/eventBus';
import { searchEventbriteEvents, hasEventbriteKey } from '../../lib/eventbrite';
import { serpGoogleEvents, hasSerpApiKey } from '../../lib/serpapi';

const MIN_INTERVAL_MS = 3 * 24 * 60 * 60 * 1000; // 3 days — runs twice a week via scheduler

const TYPE_ICON: Record<string, string> = {
  concert: '🎵', conference: '🎙️', festival: '🎪', market: '🛒',
  sports: '⚽', community: '🤝', exhibition: '🖼️', tv_broadcast: '📺',
  other: '📍',
};

/**
 * findLocalEvents — discovers upcoming concerts, festivals and events
 * near the business location using targeted Tavily searches on Israeli
 * event listing sites (Timeout, goout.net, icast, etc.).
 *
 * Each found event gets a business-specific CTA generated by the LLM.
 * Runs automatically as part of runFullScan (every 12h).
 */
export async function findLocalEvents(req: Request, res: Response) {
  const { businessProfileId, force } = req.body;
  if (!businessProfileId) return res.status(400).json({ error: 'Missing businessProfileId' });

  // Scheduler uses the 3-day guard; manual scan from the UI passes force:true to bypass it
  if (!force && shouldSkipAgent(businessProfileId, 'findLocalEvents', MIN_INTERVAL_MS)) {
    return res.json({ signals_created: 0, skipped: true, reason: 'ran_recently' });
  }

  const startTime = new Date().toISOString();
  try {
    const profile = await prisma.businessProfile.findFirst({ where: { id: businessProfileId } });
    if (!profile) return res.status(404).json({ error: 'No business profile' });

    const { name, category, city } = profile;
    const now = new Date();
    const month      = now.toLocaleDateString('he-IL', { month: 'long' });
    const nextMonth  = new Date(now.getTime() + 30 * 86400000).toLocaleDateString('he-IL', { month: 'long' });
    const yearStr    = now.getFullYear();

    // Derive a region label for small cities that aren't indexed heavily
    // e.g. "זכרון יעקב" → also search "כרמל", "שרון"; "אילת" → "נגב" etc.
    const REGION_MAP: Record<string, string> = {
      'זכרון יעקב': 'כרמל שרון קיסריה',
      'בנימינה': 'כרמל שרון קיסריה',
      'עתלית': 'כרמל חיפה',
      'מגדל העמק': 'עמק יזרעאל',
      'עפולה': 'עמק יזרעאל',
      'כפר סבא': 'שרון',
      'רעננה': 'שרון',
      'הרצליה': 'גוש דן',
      'נס ציונה': 'גוש דן',
      'אשדוד': 'שפלה',
      'אשקלון': 'שפלה',
      'באר שבע': 'נגב',
      'אילת': 'נגב',
    };
    const CITY_EN_MAP: Record<string, string> = {
      'תל אביב': 'Tel Aviv', 'ירושלים': 'Jerusalem', 'חיפה': 'Haifa',
      'באר שבע': 'Beer Sheva', 'אילת': 'Eilat', 'נתניה': 'Netanya',
      'ראשון לציון': 'Rishon LeZion', 'פתח תקוה': 'Petah Tikva',
      'אשדוד': 'Ashdod', 'אשקלון': 'Ashkelon', 'הרצליה': 'Herzliya',
      'רעננה': 'Raanana', 'כפר סבא': 'Kfar Saba', 'נס ציונה': 'Nes Ziona',
      'עפולה': 'Afula', 'מגדל העמק': 'Migdal HaEmek', 'עתלית': 'Atlit',
      'בנימינה': 'Binyamina', 'זכרון יעקב': 'Zichron Yaakov',
    };
    const cityEn = CITY_EN_MAP[city] || city;
    const regionTerms = REGION_MAP[city] || '';

    if (isTavilyRateLimited()) {
      return res.json({ signals_created: 0, message: 'Tavily rate limited' });
    }

    // ── Targeted queries: Israeli event listing sites + sports ────────────────
    const areaTerms = [city, regionTerms].filter(Boolean).join(' ');

    // ── Phase 0: Eventbrite API — structured event data (direct API, not search) ─
    const eventbriteRaw: any[] = [];
    if (hasEventbriteKey()) {
      try {
        const [ebGeneral, ebCategory] = await Promise.all([
          searchEventbriteEvents(city, `${category} ${city}`, 60, 15),
          searchEventbriteEvents(city, city, 45, 10),
        ]);
        for (const ev of [...ebGeneral, ...ebCategory]) {
          if (!ev.name || !ev.start_utc) continue;
          eventbriteRaw.push({
            name:               ev.name,
            date_iso:           ev.start_utc.slice(0, 10),
            date_text:          new Date(ev.start_utc).toLocaleDateString('he-IL', { day: 'numeric', month: 'long', year: 'numeric' }),
            venue:              ev.venue_name || city,
            type:               'other',
            artist_or_headliner: ev.category || null,
            expected_crowd:     (ev.capacity && ev.capacity > 500) ? 'large' : 'medium',
            traffic_impact:     (ev.capacity && ev.capacity > 500) ? 'high' : 'medium',
            business_opportunity: `לקוחות האירוע "${ev.name}" עשויים לבקר ב${name} לפני/אחרי האירוע`,
            source_url:         ev.url || null,
            _source:            'eventbrite_api',
          });
        }
        console.log(`[findLocalEvents] Eventbrite API: ${eventbriteRaw.length} events in ${city}`);
      } catch (e: any) {
        console.warn('[findLocalEvents] Eventbrite error:', e.message);
      }
    }

    // ── Phase 0.5: SerpAPI Google Events ─────────────────────────────────────
    const serpEventRaw: any[] = [];
    if (hasSerpApiKey()) {
      try {
        const [serpCity, serpHeb] = await Promise.all([
          serpGoogleEvents(`events in ${cityEn} Israel ${month} ${yearStr}`, `${cityEn}, Israel`),
          serpGoogleEvents(`אירועים הופעות ${city} ${month} ${yearStr}`, `${cityEn}, Israel`),
        ]);
        const serpAll = [...serpCity, ...serpHeb];
        // ponytail: thin-result region fallback — only fires for small towns in REGION_MAP
        if (serpAll.length < 3 && regionTerms) {
          const firstRegion = regionTerms.split(' ')[0];
          const serpRegion = await serpGoogleEvents(`אירועים ${regionTerms} ${month} ${yearStr}`, `${firstRegion}, Israel`);
          serpAll.push(...serpRegion);
        }
        for (const ev of serpAll) {
          if (!ev.title || !ev.date?.start_date) continue;
          serpEventRaw.push({
            name:               ev.title,
            date_iso:           ev.date.start_date || null,
            date_text:          ev.date.when || ev.date.start_date || '',
            venue:              ev.venue?.name || ev.address?.[0] || city,
            type:               'other',
            artist_or_headliner: ev.title,
            expected_crowd:     'medium',
            traffic_impact:     'medium',
            business_opportunity: `לקוחות "${ev.title}" ב${city} — הזדמנות ל${name}`,
            source_url:         ev.link || ev.ticket_info?.[0]?.link || null,
            _source:            'serpapi_events',
          });
        }
        console.log(`[findLocalEvents] SerpAPI Events: ${serpEventRaw.length} events for ${city}`);
      } catch (e: any) {
        console.warn('[findLocalEvents] SerpAPI Events error:', e.message);
      }
    }

    const lower = category.toLowerCase();

    // ── Batch 1: Local events — sector-aware queries ──────────────────────────
    const localEventQueries: string[] = [
      `site:kupat.co.il הופעה פסטיבל אירוע ${areaTerms} ${month} ${nextMonth} ${yearStr}`,
      `site:leaan.co.il הופעה פסטיבל אירוע ${areaTerms} ${month} ${nextMonth} ${yearStr}`,
      `site:timeout.co.il הופעות פסטיבלים אירועים ${city} ${month} ${nextMonth}`,
      `הופעה זמר להקה פסטיבל אירוע ${areaTerms} ${month} ${nextMonth} ${yearStr} כרטיסים`,
      `ירייד שוק אוכל פסטיבל ${areaTerms} ${month} ${nextMonth} ${yearStr}`,
    ];

    // Tech / startup / digital / design sector — professional events
    if (['tech', 'software', 'startup', 'digital', 'design', 'ui', 'ux', 'saas', 'product', 'developer', 'סטארטאפ', 'טכנולוגיה', 'עיצוב', 'תוכנה'].some(k => lower.includes(k))) {
      localEventQueries.push(`startup tech conference meetup event Israel ${city} ${month} ${yearStr}`);
      localEventQueries.push(`כנס טכנולוגיה סטארטאפ עיצוב UX ${city} ${month} ${yearStr}`);
      localEventQueries.push(`UX design product management event meetup Israel ${month} ${yearStr}`);
      localEventQueries.push(`hackathon developer event Israel ${month} ${yearStr}`);
    }
    // Beauty / fashion
    if (['יופי', 'beauty', 'מספרה', 'salon', 'spa', 'ספא', 'אופנה', 'fashion'].some(k => lower.includes(k))) {
      localEventQueries.push(`תצוגת אופנה כנס יופי מופע קוסמטיקה ${city} ${month} ${nextMonth} ${yearStr}`);
    }
    // Food / restaurant / cafe
    if (['מסעדה', 'אוכל', 'food', 'restaurant', 'בית קפה', 'cafe', 'קייטרינג'].some(k => lower.includes(k))) {
      localEventQueries.push(`פסטיבל אוכל שוק אוכל ירייד קולינרי ${city} ${month} ${nextMonth} ${yearStr}`);
    }
    // Fitness / wellness
    if (['כושר', 'fitness', 'gym', 'יוגה', 'yoga', 'פילאטיס', 'pilates'].some(k => lower.includes(k))) {
      localEventQueries.push(`מרוץ ריצה תחרות ספורט אירוע בריאות ${city} ${month} ${nextMonth} ${yearStr}`);
    }

    // ── Batch 2: Sports matches — IL only, high traffic potential ────────────
    const sportsQueries = [
      `ישראל נבחרת כדורגל משחק קרוב ${month} ${nextMonth} 2026 יריב תאריך`,
      `ליגת העל ישראל כדורגל לוח משחקים ${month} ${nextMonth} 2026`,
      `ישראל כדורסל ליגה לאומית אירופה ${month} 2026 משחק`,
    ];

    const allResults: any[] = [];
    for (const q of localEventQueries) {
      if (isTavilyRateLimited()) break;
      const results = await tavilySearch(q, 4);
      allResults.push(...results);
    }
    const sportsResults: any[] = [];
    for (const q of sportsQueries) {
      if (isTavilyRateLimited()) break;
      const results = await tavilySearch(q, 5);
      sportsResults.push(...results);
    }

    // Deduplicate combined results by URL
    const seen = new Set<string>();
    const dedup = (arr: any[]) => arr.filter(r => {
      if (!r.url || seen.has(r.url)) return false;
      seen.add(r.url);
      return true;
    });
    const uniqueLocal   = dedup(allResults);
    const uniqueSports  = dedup(sportsResults);

    if (uniqueLocal.length === 0 && uniqueSports.length === 0 &&
        eventbriteRaw.length === 0 && serpEventRaw.length === 0) {
      setLastRun(businessProfileId, 'findLocalEvents');
      await writeAutomationLog('findLocalEvents', businessProfileId, startTime, 0);
      return res.json({ signals_created: 0 });
    }

    const localContext = uniqueLocal.slice(0, 12)
      .map(r => `[${r.url}]\n${r.title || ''}: ${(r.content || '').slice(0, 220)}`)
      .join('\n\n');

    const sportsContext = uniqueSports.slice(0, 10)
      .map(r => `[${r.url}]\n${r.title || ''}: ${(r.content || '').slice(0, 220)}`)
      .join('\n\n');

    // Eventbrite + SerpAPI already structured — pass as context for the LLM
    const structuredEventContext = [...eventbriteRaw, ...serpEventRaw].slice(0, 15)
      .map(e => `[${e._source}] ${e.name} | ${e.date_iso} | ${e.venue} | ${e.source_url || ''}`)
      .join('\n');

    // ── LLM: extract specific events with team names, artist names and real dates ─
    let events: any[] = [];
    try {
      const analysis: any = await invokeLLM({
        model: 'sonnet',
        maxTokens: 1100,
        skipCache: true,
        prompt: `אתה מומחה אירועים ושיווק עסקי בישראל. זהה אירועים ספציפיים שיכולים לייצר תנועה לעסק "${name}" (${category} ב${city}).

== אירועים מובנים (Eventbrite API + Google Events) — מקור ראשוני אמין ==
${structuredEventContext || 'אין נתונים מובנים'}

== אירועים מקומיים (הופעות, פסטיבלים, שווקים) ==
${localContext.slice(0, 2000)}

== משחקי ספורט ישראלים ==
${sportsContext.slice(0, 1600)}

חוקים קריטיים:
- שם האירוע חייב להיות ספציפי: "מכבי תל אביב נגד הפועל ירושלים" לא "משחק כדורגל", "הופעת אייגל" לא "הופעה", "פסטיבל הג'אז של חיפה" לא "פסטיבל"
- תאריך: חובה תאריך מדויק YYYY-MM-DD מתוך המקורות. אם אין תאריך ספציפי (יום+חודש+שנה) — דלג על האירוע לחלוטין. אל תמציא תאריכים.
- אל תכלול אירועים שתאריכם הוא היום בדיוק (${now.toISOString().slice(0, 10)})
- רק אירועים בחודשיים הקרובים (עד ${nextMonth} ${yearStr})
- relevance_score: 0-100 — כמה האירוע הזה רלוונטי ספציפית לעסק "${name}" (${category}).
  דוגמאות: הופעת מוזיקה למסעדה = 85, הופעת מוזיקה למפתח תוכנה = 20, כנס UX לחברת UX = 95, כנס UX למסעדה = 15, גל חום לחנות מזגנים = 90
- אירועים עם relevance_score מתחת ל-50 — אל תכלול בתגובה
- action_type: "social_post" (אירוע שיחצין עבור העסק עכשיו), "create_campaign" (דורש הכנה מראש), "create_offer" (הזדמנות למבצע)
- business_opportunity: ספציפי לסקטור "${category}" — מה הלקוחות של האירוע הזה יצטרכו מ"${name}"? עד 10 מילים

החזר JSON בלבד:
{"events":[{
  "name": "שם ספציפי",
  "date_iso": "YYYY-MM-DD",
  "date_text": "תאריך קריא בעברית",
  "venue": "מיקום האירוע",
  "type": "concert|festival|market|sports|conference|exhibition|community|tv_broadcast|other",
  "artist_or_headliner": "שם האמן / קבוצות / שם הפסטיבל",
  "expected_crowd": "large|medium|small",
  "traffic_impact": "high|medium|low",
  "relevance_score": 0-100,
  "action_type": "social_post|create_campaign|create_offer",
  "business_opportunity": "הזדמנות ספציפית ל${category} — עד 10 מילים",
  "source_url": "URL המקור",
  "provenance": "eventbrite|serpapi|tavily — העתק מתווית [source] בסעיף האירועים המובנים; השתמש ב-tavily לאירועים מחיפוש בלבד"
}]}
אם אין שום אירוע רלוונטי (relevance_score >= 50) — החזר {"events":[]}`,
        response_json_schema: { type: 'object' },
      });
      events = (analysis?.events || [])
        .filter((e: any) =>
          e.name &&
          e.date_iso &&                              // require confirmed date — no fallback
          (e.relevance_score ?? 100) >= 50           // skip irrelevant events (default 100 for legacy)
        );
    } catch (_) {}

    if (events.length === 0) {
      setLastRun(businessProfileId, 'findLocalEvents');
      await writeAutomationLog('findLocalEvents', businessProfileId, startTime, 0);
      return res.json({ signals_created: 0 });
    }

    // ── Dedup against existing local_event signals (14 days) ─────────────────
    const existing = await prisma.marketSignal.findMany({
      where: {
        linked_business: businessProfileId,
        category: 'local_event',
        detected_at: { gte: new Date(Date.now() - 14 * 86400000).toISOString() },
      },
      select: { summary: true },
    });
    const existingNames = new Set(existing.map(s => s.summary.toLowerCase()));

    // Parse sector_profile to determine which event types are irrelevant
    let irrelevantEventTypes: string[] = [];
    if (profile.sector_profile) {
      try {
        const sp = JSON.parse(profile.sector_profile);
        irrelevantEventTypes = sp.irrelevant_signal_types || [];
      } catch {}
    }

    let created = 0;
    for (const ev of events.slice(0, 8)) {
      if (existingNames.has(ev.name.toLowerCase())) continue;

      // Skip past events and today's events
      if (ev.date_iso) {
        const eventMs = new Date(ev.date_iso).getTime();
        if (eventMs < Date.now() + 86400000) continue;
      }

      // Skip event types that are irrelevant for this business's sector
      if (irrelevantEventTypes.includes(ev.type) || irrelevantEventTypes.includes('local_event')) continue;

      const icon = TYPE_ICON[ev.type] || '📍';
      const daysAway = ev.date_iso
        ? Math.ceil((new Date(ev.date_iso).getTime() - Date.now()) / 86400000)
        : null;

      // Generate business-specific CTA
      let prefilledText = '';
      try {
        const ctaRes = await invokeLLM({
          model: 'haiku',
          maxTokens: 180,
          prompt: `כתוב פוסט שיווק קצר (2-3 שורות) לעסק "${name}" (${category} ב${city}) לרגל האירוע הקרוב: "${ev.name}"${ev.artist_or_headliner ? ` עם ${ev.artist_or_headliner}` : ''} ב${ev.venue || city}${daysAway ? ` (בעוד ${daysAway} ימים)` : ''}.
הזדמנות: ${ev.business_opportunity}
מבנה: Hook + ערך ספציפי + CTA. עברית בלבד, עם אמוג'י. כתוב רק את הפוסט.`,
        });
        prefilledText = typeof ctaRes === 'string' ? ctaRes.trim() : '';
      } catch (_) {}

      await prisma.marketSignal.create({
        data: {
          summary: ev.name,
          category: 'local_event',
          impact_level: ev.traffic_impact === 'high' || ev.expected_crowd === 'large' ? 'high' : 'medium',
          recommended_action: ev.business_opportunity || `נצל את ${ev.name}`,
          confidence: ev.source_url ? 80 : 65,
          source_signals: ev.provenance === 'eventbrite' ? 'eventbrite' : ev.provenance === 'serpapi' ? 'serp_events' : 'tavily_il',
          source_description: JSON.stringify({
            event_type:           ev.type,
            artist_or_headliner:  ev.artist_or_headliner || null,
            venue:                ev.venue || null,
            date_text:            ev.date_text || null,
            event_date:           ev.date_iso || null,
            days_away:            daysAway,
            traffic_impact:       ev.traffic_impact || null,
            relevance_score:      ev.relevance_score || null,
            source_url:           ev.source_url || null,
            action_type:          ev.action_type || 'social_post',
            action_window_days:   ev.action_type === 'create_campaign' ? 14 : 7,
            action_label:         `${icon} ${ev.name}`,
            prefilled_text:       prefilledText,
            time_minutes:         10,
          }),
          agent_name: `${icon} ${ev.name}`,
          is_read: false,
          detected_at: new Date().toISOString(),
          linked_business: businessProfileId,
        },
      }).catch(() => {});

      // Publish to OTX-001 event bus for downstream orchestration
      const busEventType = ev.type === 'sports' ? 'sports_match' : 'local_event';
      publishEvent({
        businessId:  businessProfileId,
        eventType:   busEventType,
        source:      'findLocalEvents',
        payload:     { name: ev.name, type: ev.type, date_iso: ev.date_iso, traffic_impact: ev.traffic_impact },
        contextAttrs: { city, category, impact: ev.traffic_impact === 'high' ? 'high' : 'medium' },
      }).catch(() => {});

      existingNames.add(ev.name.toLowerCase());
      created++;
    }

    setLastRun(businessProfileId, 'findLocalEvents');
    await writeAutomationLog('findLocalEvents', businessProfileId, startTime, created);
    return res.json({ signals_created: created, events_found: events.length });

  } catch (err: any) {
    console.error('[findLocalEvents] error:', err.message);
    await writeAutomationLog('findLocalEvents', businessProfileId, startTime, 0, 'failed', err.message);
    return res.status(500).json({ error: err.message });
  }
}
