import { Request, Response } from 'express';
import { prisma } from '../../db';
import { invokeLLM } from '../../lib/llm';
import { tavilySearch, isTavilyRateLimited } from '../../lib/tavily';
import { writeAutomationLog } from '../../lib/automationLog';
import { shouldSkipAgent, setLastRun } from '../../lib/agentCache';
import { publishEvent } from '../../lib/eventBus';

const MIN_INTERVAL_MS = 6 * 60 * 60 * 1000; // 6 hours — events change frequently

const TYPE_ICON: Record<string, string> = {
  concert: '🎵', conference: '🎙️', festival: '🎪', market: '🛒',
  sports: '⚽', community: '🤝', exhibition: '🖼️', other: '📍',
};

/**
 * findLocalEvents — discovers upcoming concerts, festivals and events
 * near the business location using targeted Tavily searches on Israeli
 * event listing sites (Timeout, goout.net, icast, etc.).
 *
 * Each found event gets a business-specific CTA generated by the LLM.
 * Runs automatically as part of runFullScan (every 12h).
 */
export async function findLocalEvents(req: Request, res: Response) {
  const { businessProfileId } = req.body;
  if (!businessProfileId) return res.status(400).json({ error: 'Missing businessProfileId' });

  if (shouldSkipAgent(businessProfileId, 'findLocalEvents', MIN_INTERVAL_MS)) {
    return res.json({ signals_created: 0, skipped: true, reason: 'ran_recently' });
  }

  const startTime = new Date().toISOString();
  try {
    const profile = await prisma.businessProfile.findFirst({ where: { id: businessProfileId } });
    if (!profile) return res.status(404).json({ error: 'No business profile' });

    const { name, category, city } = profile;
    const now = new Date();
    const month      = now.toLocaleDateString('he-IL', { month: 'long' });
    const nextMonth  = new Date(now.getTime() + 30 * 86400000).toLocaleDateString('he-IL', { month: 'long' });
    const yearStr    = now.getFullYear();

    // Derive a region label for small cities that aren't indexed heavily
    // e.g. "זכרון יעקב" → also search "כרמל", "שרון"; "אילת" → "נגב" etc.
    const REGION_MAP: Record<string, string> = {
      'זכרון יעקב': 'כרמל שרון קיסריה',
      'בנימינה': 'כרמל שרון קיסריה',
      'עתלית': 'כרמל חיפה',
      'מגדל העמק': 'עמק יזרעאל',
      'עפולה': 'עמק יזרעאל',
      'כפר סבא': 'שרון',
      'רעננה': 'שרון',
      'הרצליה': 'גוש דן',
      'נס ציונה': 'גוש דן',
      'אשדוד': 'שפלה',
      'אשקלון': 'שפלה',
      'באר שבע': 'נגב',
      'אילת': 'נגב',
    };
    const regionTerms = REGION_MAP[city] || '';

    if (isTavilyRateLimited()) {
      return res.json({ signals_created: 0, message: 'Tavily rate limited' });
    }

    // ── Targeted queries: Israeli event listing sites + sports ────────────────
    const areaTerms = [city, regionTerms].filter(Boolean).join(' ');

    // ── Batch 1: Local events — concerts, festivals, shows ────────────────────
    const localEventQueries = [
      `site:kupat.co.il הופעה פסטיבל אירוע ${areaTerms} ${month} ${nextMonth} ${yearStr}`,
      `site:leaan.co.il הופעה פסטיבל אירוע ${areaTerms} ${month} ${nextMonth} ${yearStr}`,
      `site:timeout.co.il הופעות פסטיבלים אירועים ${city} ${month} ${nextMonth}`,
      `site:goout.net הופעה פסטיבל ${areaTerms} ${month} ${yearStr}`,
      `הופעה זמר להקה פסטיבל אירוע ${areaTerms} ${month} ${nextMonth} ${yearStr} כרטיסים`,
      `אמפיתיאטרון מרכז תרבות יקב פארק ${areaTerms} הופעה אירוע ${month} ${yearStr}`,
      `ירייד שוק אוכל פסטיבל ${areaTerms} ${month} ${nextMonth} ${yearStr}`,
    ];

    // ── Batch 2: Sports matches — always run, high traffic potential ──────────
    // These generate massive foot traffic for restaurants/bars/retail
    const sportsQueries = [
      // International football — specific upcoming matches (next 30 days)
      `international football matches upcoming ${month} ${nextMonth} 2026 specific teams date schedule high profile`,
      `UEFA Nations League Europa League Champions League upcoming matches ${month} 2026 teams date`,
      `France Brazil Argentina England Germany Spain upcoming match 2026 ${month} date opponent`,
      // Israeli football
      `ישראל נבחרת כדורגל משחק קרוב ${month} ${nextMonth} 2026 יריב תאריך`,
      `ליגת העל ישראל כדורגל לוח משחקים ${month} ${nextMonth} 2026`,
      // Basketball + other sports
      `NBA Finals 2026 teams date schedule`,
      `ישראל כדורסל ליגה לאומית אירופה ${month} 2026 משחק`,
    ];

    const allResults: any[] = [];
    // Run local event queries
    for (const q of localEventQueries) {
      if (isTavilyRateLimited()) break;
      const results = await tavilySearch(q, 4);
      allResults.push(...results);
    }
    // Run sports queries separately
    const sportsResults: any[] = [];
    for (const q of sportsQueries) {
      if (isTavilyRateLimited()) break;
      const results = await tavilySearch(q, 5);
      sportsResults.push(...results);
    }

    // Deduplicate combined results by URL
    const seen = new Set<string>();
    const dedup = (arr: any[]) => arr.filter(r => {
      if (!r.url || seen.has(r.url)) return false;
      seen.add(r.url);
      return true;
    });
    const uniqueLocal  = dedup(allResults);
    const uniqueSports = dedup(sportsResults);

    if (uniqueLocal.length === 0 && uniqueSports.length === 0) {
      setLastRun(businessProfileId, 'findLocalEvents');
      await writeAutomationLog('findLocalEvents', businessProfileId, startTime, 0);
      return res.json({ signals_created: 0 });
    }

    const localContext = uniqueLocal.slice(0, 12)
      .map(r => `[${r.url}]\n${r.title || ''}: ${(r.content || '').slice(0, 220)}`)
      .join('\n\n');

    const sportsContext = uniqueSports.slice(0, 10)
      .map(r => `[${r.url}]\n${r.title || ''}: ${(r.content || '').slice(0, 220)}`)
      .join('\n\n');

    // ── LLM: extract specific events with team names, artist names and real dates ─
    let events: any[] = [];
    try {
      const analysis: any = await invokeLLM({
        model: 'sonnet',
        maxTokens: 1100,
        skipCache: true,
        prompt: `אתה מומחה אירועים ושיווק עסקי בישראל. זהה אירועים ספציפיים שיכולים לייצר תנועה לעסק "${name}" (${category} ב${city}).

== אירועים מקומיים (הופעות, פסטיבלים, שווקים) ==
${localContext.slice(0, 2800)}

== משחקי ספורט בינלאומיים ומקומיים ==
${sportsContext.slice(0, 2000)}

חוקים קריטיים:
- שם האירוע חייב להיות ספציפי עם פרטים: "צרפת נגד סנגל" (לא "משחק כדורגל"), "הופעת אייגל" (לא "הופעה"), "פסטיבל הג'אז של חיפה" (לא "פסטיבל")
- למשחקי כדורגל/כדורסל: ציין תמיד שתי הקבוצות/נבחרות בשם מלא — "קבוצה א נגד קבוצה ב"
- תאריך: אם יש תאריך מדויק — השתמש בו. אם יש רק חודש — הכנס את ה-1 של אותו חודש. אין מידע על תאריך — דלג על האירוע
- רק אירועים בחודשיים הקרובים (עד ${nextMonth} ${yearStr})
- קבל גם אירועים מעיירות קרובות (רדיוס 30 ק"מ)
- traffic_impact: גמר/ליגת העל/נבחרת לאומית/אמן ידוע = "high". ספורט מקומי/הופעה בינונית = "medium". שאר = "low"
- business_opportunity: ספציפי לסקטור "${category}" — מה הלקוחות של האירוע הזה יצטרכו מ"${name}"?

החזר JSON בלבד:
{"events":[{
  "name": "שם ספציפי: קבוצה א נגד קבוצה ב / שם האמן / שם הפסטיבל",
  "date_iso": "YYYY-MM-DD",
  "date_text": "תאריך קריא בעברית",
  "venue": "מיקום האירוע",
  "type": "concert|festival|market|sports|exhibition|community|conference|other",
  "artist_or_headliner": "שם האמן / שתי הקבוצות / שם הפסטיבל",
  "expected_crowd": "large|medium|small",
  "traffic_impact": "high|medium|low",
  "business_opportunity": "הזדמנות ספציפית ל${category} — עד 10 מילים",
  "source_url": "URL המקור"
}]}
אם אין שום אירוע — החזר {"events":[]}`,
        response_json_schema: { type: 'object' },
      });
      const currentMonthIso = now.toISOString().slice(0, 8) + '01';
      events = (analysis?.events || [])
        .filter((e: any) => e.name)
        .map((e: any) => ({
          ...e,
          // If LLM returned no date_iso, use first of current month as fallback
          date_iso: e.date_iso || currentMonthIso,
        }));
    } catch (_) {}

    if (events.length === 0) {
      setLastRun(businessProfileId, 'findLocalEvents');
      await writeAutomationLog('findLocalEvents', businessProfileId, startTime, 0);
      return res.json({ signals_created: 0 });
    }

    // ── Dedup against existing local_event signals (14 days) ─────────────────
    const existing = await prisma.marketSignal.findMany({
      where: {
        linked_business: businessProfileId,
        category: 'local_event',
        detected_at: { gte: new Date(Date.now() - 14 * 86400000).toISOString() },
      },
      select: { summary: true },
    });
    const existingNames = new Set(existing.map(s => s.summary.toLowerCase()));

    let created = 0;
    for (const ev of events.slice(0, 8)) {
      if (existingNames.has(ev.name.toLowerCase())) continue;

      // Skip past events
      if (ev.date_iso && new Date(ev.date_iso).getTime() < Date.now() - 86400000) continue;

      const icon = TYPE_ICON[ev.type] || '📍';
      const daysAway = ev.date_iso
        ? Math.ceil((new Date(ev.date_iso).getTime() - Date.now()) / 86400000)
        : null;

      // Generate business-specific CTA
      let prefilledText = '';
      try {
        const ctaRes = await invokeLLM({
          model: 'haiku',
          maxTokens: 180,
          prompt: `כתוב פוסט שיווק קצר (2-3 שורות) לעסק "${name}" (${category} ב${city}) לרגל האירוע הקרוב: "${ev.name}"${ev.artist_or_headliner ? ` עם ${ev.artist_or_headliner}` : ''} ב${ev.venue || city}${daysAway ? ` (בעוד ${daysAway} ימים)` : ''}.
הזדמנות: ${ev.business_opportunity}
מבנה: Hook + ערך ספציפי + CTA. עברית בלבד, עם אמוג'י. כתוב רק את הפוסט.`,
        });
        prefilledText = typeof ctaRes === 'string' ? ctaRes.trim() : '';
      } catch (_) {}

      await prisma.marketSignal.create({
        data: {
          summary: ev.name,
          category: 'local_event',
          impact_level: ev.traffic_impact === 'high' || ev.expected_crowd === 'large' ? 'high' : 'medium',
          recommended_action: ev.business_opportunity || `נצל את ${ev.name}`,
          confidence: ev.source_url ? 80 : 65,
          source_signals: 'tavily_local_search',
          source_description: JSON.stringify({
            event_type:           ev.type,
            artist_or_headliner:  ev.artist_or_headliner || null,
            venue:                ev.venue || null,
            date_text:            ev.date_text || null,
            event_date:           ev.date_iso || null,
            days_away:            daysAway,
            traffic_impact:       ev.traffic_impact || null,
            source_url:           ev.source_url || null,
            action_type:          'social_post',
            action_label:         `${icon} ${ev.name}`,
            prefilled_text:       prefilledText,
            time_minutes:         10,
          }),
          agent_name: `${icon} ${ev.name}`,
          is_read: false,
          detected_at: new Date().toISOString(),
          linked_business: businessProfileId,
        },
      }).catch(() => {});

      // Publish to OTX-001 event bus for downstream orchestration
      const busEventType = ev.type === 'sports' ? 'sports_match' : 'local_event';
      publishEvent({
        businessId:  businessProfileId,
        eventType:   busEventType,
        source:      'findLocalEvents',
        payload:     { name: ev.name, type: ev.type, date_iso: ev.date_iso, traffic_impact: ev.traffic_impact },
        contextAttrs: { city, category, impact: ev.traffic_impact === 'high' ? 'high' : 'medium' },
      }).catch(() => {});

      existingNames.add(ev.name.toLowerCase());
      created++;
    }

    setLastRun(businessProfileId, 'findLocalEvents');
    await writeAutomationLog('findLocalEvents', businessProfileId, startTime, created);
    return res.json({ signals_created: created, events_found: events.length });

  } catch (err: any) {
    console.error('[findLocalEvents] error:', err.message);
    await writeAutomationLog('findLocalEvents', businessProfileId, startTime, 0, 'failed', err.message);
    return res.status(500).json({ error: err.message });
  }
}
