CREATE TABLE IF NOT EXISTS "campaigns" (
  "id"               TEXT NOT NULL PRIMARY KEY,
  "created_date"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "linked_business"  TEXT,
  "signal_id"        TEXT,
  "signal_summary"   TEXT,
  "title"            TEXT NOT NULL,
  "platform"         TEXT,
  "objective"        TEXT,
  "post_content"     TEXT,
  "image_url"        TEXT,
  "audience_json"    TEXT,
  "daily_budget_ils" DOUBLE PRECISION,
  "campaign_days"    INTEGER,
  "total_budget_ils" DOUBLE PRECISION,
  "est_reach_low"    INTEGER,
  "est_reach_high"   INTEGER,
  "est_leads_low"    INTEGER,
  "est_leads_high"   INTEGER,
  "status"           TEXT NOT NULL DEFAULT 'draft',
  "published_at"     TIMESTAMP(3),
  "actual_reach"     INTEGER,
  "actual_clicks"    INTEGER,
  "actual_leads"     INTEGER,
  "actual_spend_ils" DOUBLE PRECISION
);
